services:
  backend:
    build:
        context: ./server
        dockerfile: Dockerfile
    container_name: nest_api
    environment:
        NODE_ENV: ${NODE_ENV}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    ports:
        - "3000:3000"
    networks:
        - app-network

  frontend:
    build:
        context: ./client
        dockerfile: Dockerfile
        args: 
          VITE_API_URL: ${VITE_API_URL}
    container_name: react_ui
    environment:
        VITE_API_URL: ${VITE_API_URL}
    ports:
        - "8080:80"
    depends_on:
        - backend
    networks:
        - app-network

networks:
    app-network:
        driver: bridge
