name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  # Build and Push Docker Images
  build-and-push:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: testaction

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: registry7401.azurecr.io
        username: registry7401
        password: ${{ secrets.ACR_PASSWORD }}

    # Extrae los primeros 7 caracteres del GITHUB_SHA, que es el hash del commit actual (por ejemplo, a1b2c3d).
    # Lo que se escribe en $GITHUB_OUTPUT puede ser usado en pasos posteriores mediante steps.<id>.outputs.<nombre>.
    - name: Set image tag
      id: vars
      run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT


    - name: Build and push frontend image
      run: |
        docker build -t registry7401.azurecr.io/topicos-api-frontend:${{ steps.vars.outputs.tag }} --build-arg VITE_API_URL://topicosapi.westus.azurecontainer.io/ ./client
        docker push registry7401.azurecr.io/topicos-api-frontend:${{ steps.vars.outputs.tag }}

    - name: Build and push backend image
      run: |
        docker build -t registry7401.azurecr.io/topicos-api-backend:${{ steps.vars.outputs.tag }} ./server
        docker push registry7401.azurecr.io/topicos-api-backend:${{ steps.vars.outputs.tag }}
